version: '3.7'

services:
    fastapi:
        build:
           context: .
           dockerfile: .docker/server/Dockerfile
        container_name: ms-server-app
        command: uvicorn server.main:app --host 0.0.0.0 --port 80 --reload
        restart: unless-stopped
        environment:
            - EDITOR=/bin/nano
        volumes:
            - ./:/home/appuser:rw,cached
        ports:
            - "8000:80"